targets:
  $default:
    builders:
      endorse_builder:
        enabled: true
  
builders:
  endorse_builder:
    import: "package:endorse/endorse.dart"
    builder_factories: ["EndorseBuilder"]
    build_extensions: {".dart": [".endorse.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]