steps:
  - name: 'gcr.io/cloud-builders/docker'
    # Use this to DISALLOW caching of assets
    # args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME', './server/', '--no-cache', '--pull' ]
    # Use this to ALLOW caching of assets
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME', './server/' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/$REPO_NAME' ]
  - name: 'gcr.io/cloud-builders/gcloud'
    # 
    #args: ['run', 'deploy', $REPO_NAME, '--platform', 'managed', '--image', 'gcr.io/$PROJECT_ID/{{REPOSITORY NAME}}', '--region', 'us-central1']
    # Allow unauthenticated access
    args: ['run', 'deploy', $REPO_NAME, '--allow-unauthenticated', '--platform', 'managed', '--image', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest', '--region', 'us-central1']
images:
  - gcr.io/$PROJECT_ID/$REPO_NAME
timeout: 840s