apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrape-dilawri-ca
  namespace: force
  labels:
    app: scrape-dilawri-ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrape-dilawri-ca
  template:
    metadata:
      labels:
        app: scrape-dilawri-ca
    spec:
      containers:
        - name: scrape-dilawri-ca
          image: gcr.io/yavin-iv/scrape-dilawri-ca
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
          env:
            - name: DGOC_APPS_HOST
              value: dgoc-apps-proxy
            - name: DGOC_APPS_PORT
              value: "5432"
            - name: DGOC_APPS_DB
              valueFrom:
                secretKeyRef:
                  name: dgoc-apps-credentials
                  key: database
            - name: DGOC_APPS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: dgoc-apps-credentials
                  key: user
            - name: DGOC_APPS_DB_PWORD
              valueFrom:
                secretKeyRef:
                  name: dgoc-apps-credentials
                  key: password