builders:
  endorse:
    target: ":endorse_builder"
    import: "package:endorse_builder/builder.dart"
    builder_factories: ["endorseBuilder"]
    build_extensions: {".dart": [".endorse.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
