name: endorse_builder
homepage: "https://github.com/kirklink/endorse"
description: "Library for validating random objects like API responses. This is the code generator."
version: 0.0.1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  endorse:
    path: ../endorse
  source_gen: ^0.9.5
  build: any
  analyzer: ^0.39.10
  recase: ^3.0.0
  # build_config: ^0.4.2
dev_dependencies:
  build_runner: ^1.10.0
  # build_verify: any
  pedantic: any
  