name: endorse_builder
homepage: "https://github.com/kirklink/endorse"
description: "Library for validating random objects like API responses. This is the code generator."
version: 0.0.28
environment:
  sdk: '>=2.9.0 <3.0.0'
dependencies:
  recase: ^4.0.0
  endorse:
    path: ../endorse
  # endorse: ^0.0.2
  source_gen: ^1.0.0
  analyzer: ^1.5.0
  build: ^2.0.1
dev_dependencies:
  build_runner: ^2.0.2
  pedantic: ^1.11.0
# dependency_overrides:
#   analyzer: ^0.39.10