name: endorse_builder
homepage: "https://github.com/kirklink/endorse"
description: "Library for validating random objects like API responses. This is the code generator."
version: 0.0.1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  endorse:
    path: ../endorse
  source_gen: ^0.9.0
  build: ^1.2.2
  analyzer: ^0.39.0
  recase: ^3.0.0
dev_dependencies:
  build_runner: any
  pedantic: any
  