name: endorse_builder
homepage: "https://github.com/kirklink/endorse"
description: "Library for validating random objects like API responses. This is the code generator."
version: 0.0.14
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  recase: ^3.0.0
  endorse:
    path: ../endorse
  # endorse: ^0.0.14
  source_gen: ^0.9.5
  analyzer: ^0.39.10
  build: ^1.3.0
dev_dependencies:
  build_runner: ^1.10.0
  pedantic: ^1.9.0
  