name: endorse_builder
homepage: "https://github.com/kirklink/endorse"
description: "Library for validating random objects like API responses. This is the code generator."
version: 0.0.25
environment:
  sdk: '>=2.9.0 <3.0.0'
dependencies:
  recase: ^3.0.0
  endorse:
    path: ../endorse
  # endorse: ^0.0.25
  source_gen: ^0.9.8
  analyzer: ^0.40.4
  build: ^1.5.1
dev_dependencies:
  build_runner: ^1.10.6
  pedantic: ^1.9.0
# dependency_overrides:
#   analyzer: ^0.39.10