name: endorse_builder
homepage: "https://github.com/kirklink/endorse"
description: "Library for validating random objects like API responses. This is the code generator."
version: 0.0.8
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  recase: ^3.0.0
  # endorse:
  #   path: ../endorse
  endorse: ^0.0.8
  source_gen: ^0.9.0
  analyzer: ^0.39.0
  
  
dev_dependencies:
  build: ^1.2.2
  build_runner: ^1.0.0
  pedantic: ^1.9.0
  