# cronjob.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scrape-dilawri-ca
  namespace: force
spec:
  schedule: "35 10 * * *"
  startingDeadlineSeconds: 100
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scrape-dilawri-ca
              image: gcr.io/yavin-iv/scrape-dilawri-ca:latest
              securityContext:
                runAsUser: 2  # non-root user
                allowPrivilegeEscalation: false
              env:
                - name: DGOC_APPS_HOST
                  value: dgoc-apps-proxy
                - name: DGOC_APPS_PORT
                  value: "5432"
                - name: DGOC_APPS_DB
                  valueFrom:
                    secretKeyRef:
                      name: dgoc-apps-credentials
                      key: database
                - name: DGOC_APPS_DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: dgoc-apps-credentials
                      key: user
                - name: DGOC_APPS_DB_PWORD
                  valueFrom:
                    secretKeyRef:
                      name: dgoc-apps-credentials
                      key: password
          restartPolicy: OnFailure
      backoffLimit: 5
      activeDeadlineSeconds: 7200