name: endorse
homepage: "https://github.com/kirklink/endorse"
description: "Library for validating arbitrary objects such as API responses."
version: 0.1.0-nullsafety.0
environment:
  sdk: '>=2.12.0 <3.0.0'
#dependencies: 
dev_dependencies:
  pedantic: ^1.11.0
  