name: endorse
homepage: "https://github.com/kirklink/endorse"
description: "Library for validating arbitrary objects such as API responses."
version: 0.0.4
environment:
  sdk: '>=2.7.0 <3.0.0'
#dependencies: 
dev_dependencies:
  build_runner: any
  pedantic: any
  